//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5_WebApplication.XmlServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XmlServiceProxy.XmlServices")]
    public interface XmlServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlServices/staffXMLUsers", ReplyAction="http://tempuri.org/XmlServices/staffXMLUsersResponse")]
        string[] staffXMLUsers(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlServices/staffXMLUsers", ReplyAction="http://tempuri.org/XmlServices/staffXMLUsersResponse")]
        System.Threading.Tasks.Task<string[]> staffXMLUsersAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlServices/accountVerification", ReplyAction="http://tempuri.org/XmlServices/accountVerificationResponse")]
        bool accountVerification(string fileName, string userName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlServices/accountVerification", ReplyAction="http://tempuri.org/XmlServices/accountVerificationResponse")]
        System.Threading.Tasks.Task<bool> accountVerificationAsync(string fileName, string userName, string passWord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XmlServicesChannel : Project5_WebApplication.XmlServiceProxy.XmlServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlServicesClient : System.ServiceModel.ClientBase<Project5_WebApplication.XmlServiceProxy.XmlServices>, Project5_WebApplication.XmlServiceProxy.XmlServices {
        
        public XmlServicesClient() {
        }
        
        public XmlServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] staffXMLUsers(string fileName) {
            return base.Channel.staffXMLUsers(fileName);
        }
        
        public System.Threading.Tasks.Task<string[]> staffXMLUsersAsync(string fileName) {
            return base.Channel.staffXMLUsersAsync(fileName);
        }
        
        public bool accountVerification(string fileName, string userName, string passWord) {
            return base.Channel.accountVerification(fileName, userName, passWord);
        }
        
        public System.Threading.Tasks.Task<bool> accountVerificationAsync(string fileName, string userName, string passWord) {
            return base.Channel.accountVerificationAsync(fileName, userName, passWord);
        }
    }
}
